# Generated by Django 4.0.6 on 2022-07-29 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0015_alter_klasa_imazhi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=200, null=True)),
                ('image', models.ImageField(default='cat_images/default.jpg', upload_to='cat_images')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=400)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='course_images')),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.class')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='lendet',
            name='klasa',
        ),
        migrations.RemoveField(
            model_name='lendet',
            name='krijues',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='pozicioni',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='titulli',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='lenda',
        ),
        migrations.DeleteModel(
            name='Klasa',
        ),
        migrations.DeleteModel(
            name='Lendet',
        ),
        migrations.AddField(
            model_name='lesson',
            name='legend',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.subject'),
            preserve_default=False,
        ),
    ]
