# Generated by Django 4.0.6 on 2022-07-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_class_subject_remove_lendet_klasa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
